{ATENÇÃO: Esta rotina ainda está em desenvolvimento.
          O código gerado pode apresentar incorreções sintáticas. }
program contando0a10;
uses Crt;
var
end;
contador: integer;
begin
begin
end;
contador := 0;
begin
end;
while (contador <= 5) do begin
begin
end;
writeln(contador);
begin
end;
contador := contador + 1;
begin
end;
end;
begin
end;
writeln ('terminei de contar', contador);
begin
end.