Algoritmo "temperatura"
//Calcular Celcius de Fahrenheit  Cº = F - 32 / 1,8
Var
// Seção de Declarações das variáveis 
    c, f: real
    
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreval ("Hmm...! Que frio...")
     escreval ("Qual é a temperatura em Fahrenheit Fº ?")
     leia(f)
     c <- (f - 32)/1.8
     escreval ("No Brasíl a temperatura seria: ", C: 4:1, "Cº")
Fimalgoritmo