Algoritmo "Curso de Algoritmos #05 com Gustavo Guanabara"
// Comando Soma
Var
// Seção de Declarações das variáveis 
   N1, N2: Inteiro
   S: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Vamos somar 2 números ")
   escreva("Diga um numero ")
   leia(N1)
   escreva("Diga outro numero ")
   leia(N2)
   S <- N1 + N2
   escreva("A soma dos valores é: ", S)
Fimalgoritmo